### ISSUE TITLE
天翼云签到bug 我也出现了Error: Request failed with status code 400

### ISSUE THREAD

**Issue by zszczh** [yi-Xu-0100/soulsign-scripts#57] opened 2022-04-08 01:46 UTC
{
"domain":
"cloud.189.cn",

"url":
"https://cloud.189.cn/web/login.html",

"message":
"Error: Request failed with status code 400",

"errno":
true

}

**Comment by yi-Xu-0100** [comment] 2022-04-08 01:57
Duplicate of #52

**Closed by yi-Xu-0100** 2022-04-08 01:57 UTC
